# Generated by Django 2.0.5 on 2019-03-06 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='entire_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120, null=True)),
                ('user', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('house', models.CharField(choices=[('flat', 'flat'), ('seperate house', 'seperate house')], default='flat', max_length=20)),
                ('rent', models.IntegerField(default=0)),
                ('securitydeposit', models.IntegerField(default=0)),
                ('Area_sqft', models.IntegerField(default=0)),
                ('bed_rooms', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('bathrooms', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('kitchen', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('hall', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('family', 'family'), ('any', 'any')], default='any', max_length=20)),
                ('Furniture', models.CharField(choices=[('full', 'full furnished'), ('semi', 'semi furnished'), ('no', 'no furnished')], default='full', max_length=20)),
                ('Available', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('essentialamenities', multiselectfield.db.fields.MultiSelectField(choices=[('parking', 'Car parking'), ('security', 'Security services'), ('water', 'Water supply'), ('elevator', 'Elevators'), ('power', 'Power backup'), ('maintenance', '24-hour maintenance')], default='parking', max_length=49)),
                ('optionalamenities', multiselectfield.db.fields.MultiSelectField(choices=[('play', 'Play area'), ('gym', 'Gym'), ('salon', 'Spa and salon'), ('Concierge', 'Concierge services'), ('hospital', 'Hospitals'), ('restaurant', 'Restaurants'), ('temples', 'Temple and religious activity place'), ('wifi', 'Wi-Fi connectivity')], default='play', max_length=57)),
                ('description', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image2', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image3', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image4', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image5', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image6', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='entire_house_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('sharedroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.entire_house')),
            ],
        ),
        migrations.CreateModel(
            name='private_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120, null=True)),
                ('user', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('rent', models.IntegerField(default=0)),
                ('securitydeposit', models.IntegerField(default=0)),
                ('Area_sqft', models.IntegerField(default=0)),
                ('bed_rooms', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('bathrooms', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('kitchen', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('hall', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('rooms_available', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('family', 'family'), ('any', 'any')], default='any', max_length=20)),
                ('Furniture', models.CharField(choices=[('full', 'full furnished'), ('semi', 'semi furnished'), ('no', 'no furnished')], default='full', max_length=20)),
                ('Available', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('essentialamenities', multiselectfield.db.fields.MultiSelectField(choices=[('parking', 'Car parking'), ('security', 'Security services'), ('water', 'Water supply'), ('elevator', 'Elevators'), ('power', 'Power backup'), ('maintenance', '24-hour maintenance')], default='parking', max_length=49)),
                ('optionalamenities', multiselectfield.db.fields.MultiSelectField(choices=[('play', 'Play area'), ('gym', 'Gym'), ('salon', 'Spa and salon'), ('Concierge', 'Concierge services'), ('hospital', 'Hospitals'), ('restaurant', 'Restaurants'), ('temples', 'Temple and religious activity place'), ('wifi', 'Wi-Fi connectivity')], default='play', max_length=57)),
                ('description', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image2', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image3', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image4', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image5', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image6', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='private_room_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('sharedroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.private_room')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='share_room_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
            ],
        ),
        migrations.CreateModel(
            name='shared_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120, null=True)),
                ('user', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('rent', models.IntegerField(default=0)),
                ('securitydeposit', models.IntegerField(default=0)),
                ('Area_sqft', models.IntegerField(default=0)),
                ('bed_rooms', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('bathrooms', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('kitchen', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('hall', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('beds_available', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('family', 'family'), ('any', 'any')], default='any', max_length=20)),
                ('Furniture', models.CharField(choices=[('full', 'full furnished'), ('semi', 'semi furnished'), ('no', 'no furnished')], default='full', max_length=20)),
                ('Available', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('essentialamenities', multiselectfield.db.fields.MultiSelectField(choices=[('parking', 'Car parking'), ('security', 'Security services'), ('water', 'Water supply'), ('elevator', 'Elevators'), ('power', 'Power backup'), ('maintenance', '24-hour maintenance')], default='parking', max_length=49)),
                ('optionalamenities', multiselectfield.db.fields.MultiSelectField(choices=[('play', 'Play area'), ('gym', 'Gym'), ('salon', 'Spa and salon'), ('Concierge', 'Concierge services'), ('hospital', 'Hospitals'), ('restaurant', 'Restaurants'), ('temples', 'Temple and religious activity place'), ('wifi', 'Wi-Fi connectivity')], default='play', max_length=57)),
                ('description', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image2', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image3', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image4', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image5', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
                ('image6', models.ImageField(blank=True, upload_to=forum.models.upload_location, verbose_name='Image(optional)')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='share_room_images',
            name='sharedroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.shared_room'),
        ),
    ]
